version: '3.0'
services:
  mysql:
    image: mysql:5.5
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=how2java
      - MYSQL_ROOT_PASSWORD=root